sudo: required
services:
  - docker

before_install:
  - docker build -t asljivar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asljivar/react-test npm test

after_success:
  - docker build -t asljivar/multi-client ./client
  - docker build -t asljivar/multi-nginx ./nginx
  - docker build -t asljivar/multi-server ./server
  - docker build -t asljivar/multi-worker ./worker
  # Log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push asljivar/multi-client
  - docker push asljivar/multi-nginx
  - docker push asljivar/multi-server
  - docker push asljivar/multi-worker
